### PR TITLE
Update 1.adoc

### PR DESCRIPTION
**Pull request by balinor2017**

### CODE REVIEW

**Review by balinorLiang — COMMENTED** [review]
The changes are wrong.

**Comment by balinor2017** [comment]
> The changes are wrong.

Okay, let me check

**Review by balinorLiang — APPROVED** [review]
Okay, no problem now!!!

**Review by balinorLiang — CHANGES_REQUESTED** [review]
Please fix typo.

**Review by balinorLiang — COMMENTED** [review]
Wait for another reviewers

**Comment by balinorLiang** [comment]
> Please fix typo.

Sorry no typo

**Review by balinorLiang — DISMISSED** [review]

**Review by balinorLiang — COMMENTED** [review]
please wait

**Pull request closed without merging**
